title: Your awesome title
author: GitHub User
email: chihacker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test Test TEst Test
# social links
twitter_username: chihacker # DO NOT include the @ character, or else the build will fail!
github_username:  chihacker # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
